-- Migration: Daily Turnover (Дневен оборот)
-- Records every payment taken, either automatically when a service card is
-- generated, or entered manually. Reception may read and create rows;
-- only admins may edit or delete them.
-- Run this in the Supabase SQL Editor.

-- ============================================
-- HELPER: is the current user a super-admin?
-- ============================================
-- SECURITY DEFINER so the policy can read profiles without recursing through
-- the profiles RLS policies.
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE auth_id = auth.uid() AND role = 'admin'
  );
$$;

GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;

-- ============================================
-- DAILY TURNOVER TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS daily_turnover (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Where the row came from: generated by a service card, or typed by hand
  source text NOT NULL DEFAULT 'manual' CHECK (source IN ('service_card', 'manual')),

  -- Link back to the offer when the row was produced by a service card
  offer_id uuid REFERENCES offers(id) ON DELETE SET NULL,
  offer_number text,
  service_card_number text,

  -- What was done
  entry_date date NOT NULL DEFAULT CURRENT_DATE,
  vehicle text,
  license_plate text,
  repair_name text,
  client_name text,

  -- How it was paid
  amount numeric(10,2) NOT NULL CHECK (amount >= 0),
  payment_method text NOT NULL CHECK (payment_method IN ('cash', 'card', 'bank')),

  notes text,

  -- Who recorded it
  created_by_name text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE daily_turnover ENABLE ROW LEVEL SECURITY;

-- Everyone signed in can read the turnover log
DROP POLICY IF EXISTS "Authenticated users can read daily_turnover" ON daily_turnover;
CREATE POLICY "Authenticated users can read daily_turnover"
  ON daily_turnover FOR SELECT
  TO authenticated
  USING (true);

-- Reception must be able to create rows: generating a service card writes one,
-- and manual entries are part of the daily workflow.
DROP POLICY IF EXISTS "Authenticated users can insert daily_turnover" ON daily_turnover;
CREATE POLICY "Authenticated users can insert daily_turnover"
  ON daily_turnover FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Editing and deleting is admin-only — reception has no correction rights.
DROP POLICY IF EXISTS "Only admins can update daily_turnover" ON daily_turnover;
CREATE POLICY "Only admins can update daily_turnover"
  ON daily_turnover FOR UPDATE
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Only admins can delete daily_turnover" ON daily_turnover;
CREATE POLICY "Only admins can delete daily_turnover"
  ON daily_turnover FOR DELETE
  TO authenticated
  USING (public.is_admin());

-- Indexes for the day/month views
CREATE INDEX IF NOT EXISTS idx_daily_turnover_date
  ON daily_turnover (entry_date DESC);
CREATE INDEX IF NOT EXISTS idx_daily_turnover_offer
  ON daily_turnover (offer_id);
CREATE INDEX IF NOT EXISTS idx_daily_turnover_method
  ON daily_turnover (entry_date, payment_method);

-- Keep updated_at fresh
CREATE OR REPLACE FUNCTION public.touch_daily_turnover()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_daily_turnover_updated_at ON daily_turnover;
CREATE TRIGGER trg_daily_turnover_updated_at
  BEFORE UPDATE ON daily_turnover
  FOR EACH ROW EXECUTE FUNCTION public.touch_daily_turnover();
